apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
scopes:
  - client-daprized
  - service-daprized
spec:
  policies:
    timeouts:
      general: 3s
      important: 60s
      largeResponse: 10s

    retries:
      retryForever:
        policy: exponential
        maxInterval: 15s
        maxRetries: -1 # retry indefinitely

      important:
        policy: constant
        duration: 3s
        maxRetries: 3

    circuitBreakers:
      simpleCB:
        maxRequests: 5
        maxFailures: 5    
        timeout: 30s 
        trip: consecutiveFailures >= 5

  targets:
    apps:
      service-daprized:
        timeout: general
        retry: important
        # circuit breakers for services are scoped app instance.
        # when a breaker is tripped, that route is removed from load balancing for the configured `timeout` duration.
        #circuitBreaker: simpleCB
